### PR TITLE
add snazzymenu.js

### PR DESCRIPTION
**Pull request by teloe**
add snazzymenu.js mega menu

### CODE REVIEW

**Comment by TixieBorg** [comment]
Hi! Thank you for your contribution and for this plugin!

Have you published it on npm? That's a great way to allow people to add then into their project and manage updates.

Also I'm not sure to understand the images in your landing page, does it have a meaning I'm missing? 

Thank you in advance for your answers

Respectfully, Tixie

**Comment by teloe** [comment]
Hi, Tixie. Thanks for your feedback. I went ahead and published on npm and updated this pr with the link to the package. The images were just random placeholders. I agree that they were confusing so I updated the landing page so it just shows the code snippet images. Let me know if you have any other questions. I appreciate your time.

**Comment by TixieBorg** [comment]
Your homepage is way better like that with code snippets!

Let me work on a thumbnail that would put highlight more your plugin's features visually, I'll come back to you 

(I'm currently also working on a new version of the site so it doesn't help balancing my free time with everything else, but I won't forgot you I promise)

**Comment by teloe** [comment]
Awesome! That sounds great, thank you.

**Comment by jcubic** [comment]
Do you plan to merge this PR? I'm about to create my own, but it looks like this hangs since April. Not sure it makes sense.

**Review by TixieSalander — APPROVED** [review]
Seems all good now!

**Pull request merged**
